### ISSUE TITLE
StoredProcedure Scripts don't run - Imported Model with Defined Stored Procedure

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#24]
I had a few stored procedures defined in my old 4.1 Model before importing it into version 6.0.0.177.  When I generate the installer project the scripts for the procedures are generated and put into the "old" path structure.  When I run the installer these scripts are not run against the database.

Steve

**Comment by gravbox** [comment]
There are a few things that you need to do in order to convert to 6+. First you need to delete the 3 mapping files SSDL, MSL, and CSDL. There are also some path changes like you said. The easiest thing to do is generate a 6 version in a new folder and compare the out put. There are a few files that you might need to move. It is not a big difference but the one time change does require you move/delete some stuff. Please just compare 2 generations.

**Comment by midnight-sun** [comment]
Worked as suggested.  Thanks Chris.
