### ISSUE TITLE
Code Generation - VS 2012 and VS2015

### ISSUE THREAD

**Issue by lochiano** [nHydrate/nHydrate#39]
Ok....I must be an idiot, I can easily install the nHydrate extension in both Visual Studio 2012 and 2015.   I can add a new hHydrate item in both versions, and the designer appears to work perfectly.   

  However, I am stuck on how to generate C# code from these diagrams.   The documentation seems to indicate that there should be a Generate command under tools, but I have not been able to locate it (or an equivalent) anywhere.

 Please help this idiot that only has 30+ years of development experience.

**Comment by gravbox** [comment]
Sorry I am a right-clicker. It was easier that way. On the model canvas, everything is on the right-click menu. In the toolbox add some entities, relationships, etc. Then right click on the background canvas and there is a generate menu. This will validate and if valid generate the model. There are 2 projects that you will generate. An installer and the C# EFDAL. The install can be run in debug after generation to create a matching database. To the C# project, you will need to add the Nuget package Entity Framework 6.1.3. After that it should compile fine. You can then add a connection string to the web/app config file or specify a connection string in code when you declare the context. Good luck.

**Comment by lochiano** [comment]
Thank you for the quick reply.   I did find the generate command while you were so kind as to provide an answer, there were no errors displayed.   Unfortunately, I have still not been able to locate the generated project or code.    Is there a particular location where this is saved?   Perhaps the issue is that I already started with a project, and when I added the nHydrate object, I provided the "project name" as the save name as the existing project.

**Comment by lochiano** [comment]
Ok..I found the issue.  As a test I had checked both using both SQL Server and MySQL.   It did not like MsSQL.   I turned that off and the code generated.   It was also not obvious that the code would be generated and stored in a sub directory of my original project directory.   As I mentioned before....idiot.

Thank you both for your attention to this question and for the creation of this brilliant tool.

**Comment by gravbox** [comment]
It actually works better than that. Create a blank solution. Then create a project. I always just create a blank console app. Then add an nHydrate model to the project. When you create a blank solution it is in a folder. The new project is in a sub-folder. When you generate, all projects are put at the solution level. It makes more sense that way huh? Basically all projects are created at the same level. Since you only had one project it went down a folder and added projects probably where you did not want them. Just start with a blank solution first and you will be fine. The MySql template most like no longer works. The 2 templates are being actually developed are the SQL Server installer and the EF Code first module. These are actively worked on and with bug fixes and the like. MySql was an experiment and will probably be removed soon.
